import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import 'material-symbols';

const roboto = Roboto({
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Psychology Research Agent",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`font-roboto h-full antialiased`}
    >
      <body className="min-h-full flex flex-col ">{children}</body>
    </html>
  );
}
